### ISSUE TITLE
Intermittent big-sur-xcode failures when starting up VMs

### ISSUE THREAD

**Issue by ibuclaw** [cirruslabs/macos-image-templates#46]
> Persistent worker failed to start the task: Parallels isolation failed: failed to create VM cloned from "big-sur-xcode-13": Parallels VM operation failed: failed to get info for VM with "big-sur-xcode-13" UUID or name: Parallels command returned non-zero exit code: ""

Likely the same as #45 again, as this does crop up every couple of month after being fixed.
https://cirrus-ci.com/task/5744194047180800

(We'll likely remove 10.15 at some point later this year anyway).

**Comment by fkorotkov** [comment]
Sorry for the inconveniences. I was messing with the macOS infrastructure a bit yesterday and might affected you. Should be working now.

**Comment by dkorpel** [comment]
It's still happening: https://cirrus-ci.com/task/6015270790627328
